// Copyright Bode Software. All Rights Reserved.

#include "Plan/OlivePinManifest.h"

// UE includes
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node.h"
#include "K2Node_Event.h"
#include "K2Node_CustomEvent.h"
#include "K2Node_CallFunction.h"

// JSON
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"

DEFINE_LOG_CATEGORY(LogOlivePinManifest);

// ============================================================================
// FOlivePinManifest::Build
// ============================================================================

FOlivePinManifest FOlivePinManifest::Build(
	UEdGraphNode* Node,
	const FString& StepId,
	const FString& NodeId,
	const FString& NodeType)
{
	FOlivePinManifest Manifest;

	if (!Node)
	{
		UE_LOG(LogOlivePinManifest, Warning,
			TEXT("Build() called with nullptr node for step '%s' (node '%s', type '%s')"),
			*StepId, *NodeId, *NodeType);
		Manifest.StepId = StepId;
		Manifest.NodeId = NodeId;
		Manifest.NodeType = NodeType;
		return Manifest;
	}

	// Initialize manifest fields
	Manifest.StepId = StepId;
	Manifest.NodeId = NodeId;
	Manifest.NodeType = NodeType;

	// If the node is a UK2Node_CallFunction, extract the resolved function name
	if (UK2Node_CallFunction* CallFuncNode = Cast<UK2Node_CallFunction>(Node))
	{
		UFunction* Function = CallFuncNode->GetTargetFunction();
		if (Function)
		{
			Manifest.ResolvedFunctionName = Function->GetName();
		}
	}

	// Iterate all pins on the node
	for (UEdGraphPin* Pin : Node->Pins)
	{
		// Skip null pins
		if (!Pin)
		{
			continue;
		}

		// Skip hidden data pins (like WorldContextObject, self pins).
		// We NEVER skip hidden exec pins -- some nodes have hidden exec pins
		// that are still wirable.
		if (Pin->bHidden && Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_Exec)
		{
			continue;
		}

		// Create the manifest entry
		FOlivePinManifestEntry Entry;
		Entry.PinName = Pin->GetName();
		Entry.DisplayName = Pin->GetDisplayName().ToString();
		Entry.bIsInput = (Pin->Direction == EGPD_Input);
		Entry.PinCategory = Pin->PinType.PinCategory.ToString();
		Entry.bIsExec = (Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec);
		Entry.bIsHidden = Pin->bHidden;
		Entry.bIsConnected = Pin->HasAnyConnections();
		Entry.IRTypeCategory = ConvertPinTypeToIRCategory(Pin->PinType);

		// Subcategory: extract from PinSubCategoryObject or PinSubCategory
		if (Pin->PinType.PinSubCategoryObject.IsValid())
		{
			Entry.PinSubCategory = Pin->PinType.PinSubCategoryObject->GetName();
		}
		else
		{
			Entry.PinSubCategory = Pin->PinType.PinSubCategory.ToString();
		}

		// Type display string using UE's built-in formatter
		Entry.TypeDisplayString = UEdGraphSchema_K2::TypeToText(Pin->PinType).ToString();

		// Default value: prefer DefaultValue, fall back to AutogeneratedDefaultValue
		Entry.bHasDefaultValue = (!Pin->DefaultValue.IsEmpty() || !Pin->AutogeneratedDefaultValue.IsEmpty());
		Entry.DefaultValue = Pin->DefaultValue.IsEmpty() ? Pin->AutogeneratedDefaultValue : Pin->DefaultValue;

		// Determine if this pin is required for correct node operation.
		// Required pins that are unwired will cause compile errors or wrong behavior.
		Entry.bIsRequired = false;
		if (Entry.bIsExec && Entry.bIsInput)
		{
			// Exec input is required on non-event impure nodes (events are entry points)
			UK2Node* K2Node = Cast<UK2Node>(Node);
			if (K2Node)
			{
				Entry.bIsRequired = !K2Node->IsA<UK2Node_Event>() &&
				                    !K2Node->IsA<UK2Node_CustomEvent>();
			}
		}
		else if (!Entry.bIsExec && Entry.bIsInput && !Entry.bIsHidden)
		{
			// Self/Target pin on non-static member functions
			if (Pin->GetFName() == UEdGraphSchema_K2::PN_Self)
			{
				UK2Node_CallFunction* CallFunc = Cast<UK2Node_CallFunction>(Node);
				if (CallFunc)
				{
					UFunction* Func = CallFunc->GetTargetFunction();
					Entry.bIsRequired = Func && !Func->HasAnyFunctionFlags(FUNC_Static);
				}
			}
		}

		Manifest.Pins.Add(MoveTemp(Entry));
	}

	// Determine exec pin presence
	Manifest.bHasExecPins = Manifest.Pins.ContainsByPredicate(
		[](const FOlivePinManifestEntry& E) { return E.bIsExec; });
	Manifest.bIsPure = !Manifest.bHasExecPins;

	UE_LOG(LogOlivePinManifest, Verbose,
		TEXT("Built manifest for step '%s' (node '%s', type '%s'): %d pins (%s)"),
		*StepId, *NodeId, *NodeType, Manifest.Pins.Num(),
		Manifest.bIsPure ? TEXT("pure") : TEXT("exec"));

	return Manifest;
}

// ============================================================================
// FOlivePinManifest::ConvertPinTypeToIRCategory
// ============================================================================

EOliveIRTypeCategory FOlivePinManifest::ConvertPinTypeToIRCategory(const FEdGraphPinType& PinType)
{
	// Replicate the mapping from FOlivePinSerializer::MapPinCategory
	// to avoid coupling to the reader subsystem
	static const TMap<FName, EOliveIRTypeCategory> CategoryMap = []()
	{
		TMap<FName, EOliveIRTypeCategory> Map;

		// Execution
		Map.Add(UEdGraphSchema_K2::PC_Exec, EOliveIRTypeCategory::Exec);

		// Primitives
		Map.Add(UEdGraphSchema_K2::PC_Boolean, EOliveIRTypeCategory::Bool);
		Map.Add(UEdGraphSchema_K2::PC_Byte, EOliveIRTypeCategory::Byte);
		Map.Add(UEdGraphSchema_K2::PC_Int, EOliveIRTypeCategory::Int);
		Map.Add(UEdGraphSchema_K2::PC_Int64, EOliveIRTypeCategory::Int64);
		Map.Add(UEdGraphSchema_K2::PC_Float, EOliveIRTypeCategory::Float);
		Map.Add(UEdGraphSchema_K2::PC_Double, EOliveIRTypeCategory::Double);
		Map.Add(UEdGraphSchema_K2::PC_Real, EOliveIRTypeCategory::Float);

		// Strings
		Map.Add(UEdGraphSchema_K2::PC_String, EOliveIRTypeCategory::String);
		Map.Add(UEdGraphSchema_K2::PC_Name, EOliveIRTypeCategory::Name);
		Map.Add(UEdGraphSchema_K2::PC_Text, EOliveIRTypeCategory::Text);

		// Complex types
		Map.Add(UEdGraphSchema_K2::PC_Struct, EOliveIRTypeCategory::Struct);
		Map.Add(UEdGraphSchema_K2::PC_Object, EOliveIRTypeCategory::Object);
		Map.Add(UEdGraphSchema_K2::PC_Class, EOliveIRTypeCategory::Class);
		Map.Add(UEdGraphSchema_K2::PC_Interface, EOliveIRTypeCategory::Interface);
		Map.Add(UEdGraphSchema_K2::PC_Enum, EOliveIRTypeCategory::Enum);

		// Delegates
		Map.Add(UEdGraphSchema_K2::PC_Delegate, EOliveIRTypeCategory::Delegate);
		Map.Add(UEdGraphSchema_K2::PC_MCDelegate, EOliveIRTypeCategory::MulticastDelegate);

		// Soft references (map to underlying types)
		Map.Add(UEdGraphSchema_K2::PC_SoftObject, EOliveIRTypeCategory::Object);
		Map.Add(UEdGraphSchema_K2::PC_SoftClass, EOliveIRTypeCategory::Class);

		// Wildcard
		Map.Add(UEdGraphSchema_K2::PC_Wildcard, EOliveIRTypeCategory::Wildcard);

		return Map;
	}();

	// Handle container types
	if (PinType.IsArray())
	{
		return EOliveIRTypeCategory::Array;
	}
	if (PinType.IsSet())
	{
		return EOliveIRTypeCategory::Set;
	}
	if (PinType.IsMap())
	{
		return EOliveIRTypeCategory::Map;
	}

	const EOliveIRTypeCategory* Found = CategoryMap.Find(PinType.PinCategory);
	if (Found)
	{
		// Special handling for struct subcategories that map to specific types
		if (*Found == EOliveIRTypeCategory::Struct && PinType.PinSubCategoryObject.IsValid())
		{
			FString StructName = PinType.PinSubCategoryObject->GetName();
			if (StructName == TEXT("Vector") || StructName == TEXT("Vector3f"))
			{
				return EOliveIRTypeCategory::Vector;
			}
			if (StructName == TEXT("Vector2D") || StructName == TEXT("Vector2f"))
			{
				return EOliveIRTypeCategory::Vector2D;
			}
			if (StructName == TEXT("Rotator") || StructName == TEXT("Rotator3f"))
			{
				return EOliveIRTypeCategory::Rotator;
			}
			if (StructName == TEXT("Transform") || StructName == TEXT("Transform3f"))
			{
				return EOliveIRTypeCategory::Transform;
			}
			if (StructName == TEXT("Color"))
			{
				return EOliveIRTypeCategory::Color;
			}
			if (StructName == TEXT("LinearColor"))
			{
				return EOliveIRTypeCategory::LinearColor;
			}
		}
		return *Found;
	}

	return EOliveIRTypeCategory::Unknown;
}

// ============================================================================
// FOlivePinManifest::LevenshteinDistance
// ============================================================================

int32 FOlivePinManifest::LevenshteinDistance(const FString& A, const FString& B)
{
	const int32 LenA = A.Len();
	const int32 LenB = B.Len();

	if (LenA == 0) return LenB;
	if (LenB == 0) return LenA;

	// Single-row DP: only need current and previous row
	TArray<int32> PrevRow;
	TArray<int32> CurrRow;
	PrevRow.SetNumUninitialized(LenB + 1);
	CurrRow.SetNumUninitialized(LenB + 1);

	// Initialize first row
	for (int32 j = 0; j <= LenB; ++j)
	{
		PrevRow[j] = j;
	}

	for (int32 i = 1; i <= LenA; ++i)
	{
		CurrRow[0] = i;
		for (int32 j = 1; j <= LenB; ++j)
		{
			int32 Cost = (A[i - 1] == B[j - 1]) ? 0 : 1;
			CurrRow[j] = FMath::Min3(
				PrevRow[j] + 1,       // deletion
				CurrRow[j - 1] + 1,   // insertion
				PrevRow[j - 1] + Cost  // substitution
			);
		}
		Swap(PrevRow, CurrRow);
	}

	return PrevRow[LenB];
}

// ============================================================================
// FOlivePinManifest::FindExecInput
// ============================================================================

const FOlivePinManifestEntry* FOlivePinManifest::FindExecInput() const
{
	for (const FOlivePinManifestEntry& Entry : Pins)
	{
		if (Entry.bIsExec && Entry.bIsInput && !Entry.bIsHidden)
		{
			return &Entry;
		}
	}
	return nullptr;
}

// ============================================================================
// FOlivePinManifest::FindExecOutput
// ============================================================================

const FOlivePinManifestEntry* FOlivePinManifest::FindExecOutput() const
{
	for (const FOlivePinManifestEntry& Entry : Pins)
	{
		if (Entry.bIsExec && !Entry.bIsInput && !Entry.bIsHidden)
		{
			return &Entry;
		}
	}
	return nullptr;
}

// ============================================================================
// FOlivePinManifest::FindAllExecOutputs
// ============================================================================

TArray<const FOlivePinManifestEntry*> FOlivePinManifest::FindAllExecOutputs() const
{
	TArray<const FOlivePinManifestEntry*> Result;
	for (const FOlivePinManifestEntry& Entry : Pins)
	{
		if (Entry.bIsExec && !Entry.bIsInput && !Entry.bIsHidden)
		{
			Result.Add(&Entry);
		}
	}
	return Result;
}

// ============================================================================
// FOlivePinManifest::FindDataInputByName
// ============================================================================

const FOlivePinManifestEntry* FOlivePinManifest::FindDataInputByName(const FString& Name) const
{
	for (const FOlivePinManifestEntry& Entry : Pins)
	{
		if (!Entry.bIsExec && Entry.bIsInput && !Entry.bIsHidden && Entry.PinName == Name)
		{
			return &Entry;
		}
	}
	return nullptr;
}

// ============================================================================
// FOlivePinManifest::FindDataOutputByName
// ============================================================================

const FOlivePinManifestEntry* FOlivePinManifest::FindDataOutputByName(const FString& Name) const
{
	for (const FOlivePinManifestEntry& Entry : Pins)
	{
		if (!Entry.bIsExec && !Entry.bIsInput && !Entry.bIsHidden && Entry.PinName == Name)
		{
			return &Entry;
		}
	}
	return nullptr;
}

// ============================================================================
// FOlivePinManifest::FindPinSmart
// ============================================================================

const FOlivePinManifestEntry* FOlivePinManifest::FindPinSmart(
	const FString& Hint,
	bool bIsInput,
	EOliveIRTypeCategory TypeHint,
	FString* OutMatchMethod) const
{
	// Collect candidate pins: match direction, exclude exec, exclude hidden
	// We build this filtered list once and reuse across all stages
	TArray<const FOlivePinManifestEntry*> Candidates;
	for (const FOlivePinManifestEntry& Entry : Pins)
	{
		if (Entry.bIsInput == bIsInput && !Entry.bIsExec && !Entry.bIsHidden)
		{
			Candidates.Add(&Entry);
		}
	}

	if (Candidates.IsEmpty())
	{
		return nullptr;
	}

	// ================================================================
	// Stage 1: EXACT NAME MATCH
	// ================================================================
	for (const FOlivePinManifestEntry* Entry : Candidates)
	{
		if (Entry->PinName == Hint)
		{
			if (OutMatchMethod) *OutMatchMethod = TEXT("exact");
			return Entry;
		}
	}

	// ================================================================
	// Stage 2: DISPLAY NAME MATCH
	// ================================================================
	for (const FOlivePinManifestEntry* Entry : Candidates)
	{
		if (Entry->DisplayName == Hint)
		{
			if (OutMatchMethod) *OutMatchMethod = TEXT("display_name");
			return Entry;
		}
	}

	// ================================================================
	// Stage 3: CASE-INSENSITIVE MATCH
	// ================================================================
	for (const FOlivePinManifestEntry* Entry : Candidates)
	{
		if (Entry->PinName.Equals(Hint, ESearchCase::IgnoreCase) ||
			Entry->DisplayName.Equals(Hint, ESearchCase::IgnoreCase))
		{
			if (OutMatchMethod) *OutMatchMethod = TEXT("case_insensitive");
			return Entry;
		}
	}

	// ================================================================
	// Stage 4: FUZZY MATCH (Levenshtein distance + substring)
	// ================================================================
	{
		const FOlivePinManifestEntry* Best = nullptr;
		int32 BestScore = 0;
		FString LowerHint = Hint.ToLower();

		for (const FOlivePinManifestEntry* Entry : Candidates)
		{
			int32 Score = 0;
			FString LowerPinName = Entry->PinName.ToLower();
			FString LowerDisplayName = Entry->DisplayName.ToLower();

			// Substring bonus: if either contains the other
			if (LowerPinName.Contains(LowerHint) || LowerHint.Contains(LowerPinName))
			{
				Score += 60;
			}
			if (LowerDisplayName.Contains(LowerHint) || LowerHint.Contains(LowerDisplayName))
			{
				Score += 50;
			}

			// Levenshtein distance penalty (lower distance = higher score)
			int32 LevenDist = LevenshteinDistance(LowerHint, LowerPinName);
			if (LevenDist <= 3)
			{
				Score += FMath::Max(0, 40 - LevenDist * 10);
			}

			if (Score > BestScore)
			{
				BestScore = Score;
				Best = Entry;
			}
		}

		if (Best != nullptr && BestScore >= 40)
		{
			if (OutMatchMethod) *OutMatchMethod = TEXT("fuzzy");
			UE_LOG(LogOlivePinManifest, Verbose,
				TEXT("Fuzzy matched pin hint '%s' -> '%s' (score=%d)"),
				*Hint, *Best->PinName, BestScore);
			return Best;
		}
	}

	// ================================================================
	// Stage 5: TYPE-BASED MATCH (last resort)
	// ================================================================
	if (TypeHint != EOliveIRTypeCategory::Unknown)
	{
		TArray<const FOlivePinManifestEntry*> TypeMatches;
		for (const FOlivePinManifestEntry* Entry : Candidates)
		{
			if (Entry->IRTypeCategory == TypeHint)
			{
				TypeMatches.Add(Entry);
			}
		}

		if (TypeMatches.Num() == 1)
		{
			if (OutMatchMethod) *OutMatchMethod = TEXT("type_match");
			UE_LOG(LogOlivePinManifest, Verbose,
				TEXT("Type-matched pin hint '%s' -> '%s' (type category match)"),
				*Hint, *TypeMatches[0]->PinName);
			return TypeMatches[0];
		}
		// If multiple type matches: ambiguous, fall through to failure
	}

	// ================================================================
	// Stage 6: FAILURE
	// ================================================================
	UE_LOG(LogOlivePinManifest, Warning,
		TEXT("FindPinSmart failed for hint '%s' (direction=%s). Available pins:"),
		*Hint, bIsInput ? TEXT("input") : TEXT("output"));
	for (const FOlivePinManifestEntry* Entry : Candidates)
	{
		UE_LOG(LogOlivePinManifest, Warning,
			TEXT("  - '%s' (display: '%s', type: %s)"),
			*Entry->PinName, *Entry->DisplayName, *Entry->TypeDisplayString);
	}

	return nullptr;
}

// ============================================================================
// FOlivePinManifest::GetDataPins
// ============================================================================

TArray<const FOlivePinManifestEntry*> FOlivePinManifest::GetDataPins(bool bInput) const
{
	TArray<const FOlivePinManifestEntry*> Result;
	for (const FOlivePinManifestEntry& Entry : Pins)
	{
		if (!Entry.bIsExec && Entry.bIsInput == bInput && !Entry.bIsHidden)
		{
			Result.Add(&Entry);
		}
	}
	return Result;
}

// ============================================================================
// FOlivePinManifest::ToJson
// ============================================================================

TSharedPtr<FJsonObject> FOlivePinManifest::ToJson() const
{
	TSharedPtr<FJsonObject> Json = MakeShared<FJsonObject>();

	Json->SetStringField(TEXT("step_id"), StepId);
	Json->SetStringField(TEXT("node_id"), NodeId);
	Json->SetStringField(TEXT("node_type"), NodeType);

	if (!ResolvedFunctionName.IsEmpty())
	{
		Json->SetStringField(TEXT("resolved_function"), ResolvedFunctionName);
	}

	Json->SetBoolField(TEXT("is_pure"), bIsPure);
	Json->SetBoolField(TEXT("has_exec_pins"), bHasExecPins);

	TArray<TSharedPtr<FJsonValue>> PinsArray;
	for (const FOlivePinManifestEntry& Entry : Pins)
	{
		// Skip hidden pins from JSON output (they clutter the AI's view)
		if (Entry.bIsHidden)
		{
			continue;
		}

		TSharedPtr<FJsonObject> PinJson = MakeShared<FJsonObject>();
		PinJson->SetStringField(TEXT("name"), Entry.PinName);
		PinJson->SetStringField(TEXT("display_name"), Entry.DisplayName);
		PinJson->SetStringField(TEXT("direction"), Entry.bIsInput ? TEXT("input") : TEXT("output"));
		PinJson->SetStringField(TEXT("category"), Entry.PinCategory);
		PinJson->SetBoolField(TEXT("is_exec"), Entry.bIsExec);
		PinJson->SetStringField(TEXT("type"), Entry.TypeDisplayString);

		if (!Entry.PinSubCategory.IsEmpty())
		{
			PinJson->SetStringField(TEXT("sub_category"), Entry.PinSubCategory);
		}

		if (Entry.bHasDefaultValue)
		{
			PinJson->SetBoolField(TEXT("has_default"), true);
			PinJson->SetStringField(TEXT("default_value"), Entry.DefaultValue);
		}

		if (Entry.bIsConnected)
		{
			PinJson->SetBoolField(TEXT("is_connected"), true);
		}

		if (Entry.bIsRequired)
		{
			PinJson->SetBoolField(TEXT("required"), true);
		}

		PinsArray.Add(MakeShared<FJsonValueObject>(PinJson));
	}

	Json->SetArrayField(TEXT("pins"), PinsArray);

	return Json;
}
